//
//  HouseValue.h
//  Loan
//
//  Created by JiaLi on 16/8/24.
//  Copyright © 2016年 JiaLi. All rights reserved.
///
#define RGB(r, g, b)     [UIColor colorWithRed:((r)/255.0) green:((g)/255.0) blue:((b)/255.0)     alpha:1.0]
#define RED_COLOR RGB(238, 29, 36)
#define GREEN_COLOR  RGB(124, 182, 73)
#define BLACK_COLOR RGB(0, 0, 0)

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>

typedef NS_ENUM(NSInteger, HOUSEVALUETYPE) {
    HOUSEVALUETYPE_BANNER,
    HOUSEVALUETYPE_AREA,
    HOUSEVALUETYPE_TRASACTION_PRICE,
    HOUSEVALUETYPE_NET_PRICE,
    //HOUSEVALUETYPE_HOME_VALUE,
    HOUSEVALUETYPE_ORIGINAL_VALUE,
    HOUSEVALUETYPE_FIRST,
    
    HOUSEVALUETYPE_DEED_TAX,
    //HOUSEVALUETYPE_FIVEYEARS_ONLYONE,
    HOUSEVALUETYPE_TWOYEARS,

    HOUSEVALUETYPE_PERSONAL_TAX,
    HOUSEVALUETYPE_SALE_TAX,
    HOUSEVALUETYPE_AGENCY,
    HOUSEVALUETYPE_FEESFORASSIGNMENT,
    HOUSEVALUETYPE_RATIO_OF_LOAN,
    HOUSEVALUETYPE_DOWN_PAYMENT,
    HOUSEVALUETYPE_TOTAL_PRICE,
    HOUSEVALUETYPE_SIGNLE_PRICE
};

@interface HouseStrings : NSObject

+ (NSString*)getTitle:(HOUSEVALUETYPE)type;

+ (NSString*)getInformation:(HOUSEVALUETYPE)type;

+ (BOOL)getShowSegment:(HOUSEVALUETYPE)type;

+ (BOOL)getShowTaxFiled:(HOUSEVALUETYPE)type;

+ (BOOL)getEnableFiled:(HOUSEVALUETYPE)type;

+ (BOOL)getShowUnit:(HOUSEVALUETYPE)type;

+ (UIColor*)getTextColor:(HOUSEVALUETYPE)type;
@end
